export const IMG_CDN_URL =
  'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/';

  export const LOGO_URL="https://www.flaticon.com/free-icon/cutlery_3170733?term=food&page=1&position=45&origin=search&related_id=3170733"

export const MENU_API =
  'https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=18.5415099&lng=73.7924769&restaurantId=';

export const restaurantList = [
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '306645',
      name: 'Bebe Di Rasoi - Punjabi',
      uuid: 'b2aba8e4-ac84-4e34-ad30-874d43acbfbc',
      city: '6',
      area: 'Aundh',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'f8sdl5iw9wwuu9yikvby',
      cuisines: [
        'Kebabs',
        'North Indian',
        'Chinese',
        'Mughlai',
        'Beverages',
        'Combo',
      ],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 24,
      minDeliveryTime: 24,
      maxDeliveryTime: 24,
      slaString: '24 MINS',
      lastMileTravel: 4,
      slugs: {
        restaurant: 'fml-food-music-love-shivaji-nagar-shivaji-nagar',
        city: 'pune',
      },
      cityState: '6',
      address:
        'NICE Foods, FML, Plot No 106, Pashan - Sus Rd, Vardayani Society, Baner Gaon, Pashan, Pune, Maharashtra 411021',
      locality: 'Baner Gaon',
      parentId: 230548,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'distance',
            fee: 5600,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 5600,
        message: '',
        title: 'Delivery Charge',
        amount: '5600',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=6666375~p=7~eid=00000188-49d9-c9c4-6c5b-c114004a072f',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '₹125 OFF',
        subHeader: 'ABOVE ₹249',
        discountTag: 'FLAT DEAL',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '306645',
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        lastMileTravel: 4,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.9',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '350028',
      name: 'The Chinese Factory',
      uuid: '6d845cdf-bdab-4e24-b6fa-e14864a775c5',
      city: '6',
      area: 'Pashan',
      totalRatingsString: '5000+ ratings',
      cloudinaryImageId: 'rhwb3z68ysvlh8d7ntzs',
      cuisines: ['Chinese', 'Asian', 'Beverages', 'Desserts'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 18,
      minDeliveryTime: 18,
      maxDeliveryTime: 18,
      slaString: '18 MINS',
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: 'the-chinese-factory-pimple-saudagar-pimple-saudagar',
        city: 'pune',
      },
      cityState: '6',
      address:
        'The Chinese Factory  Shop no 4, Kumar Shantiniketan Society, Opp. Amar Serenity, Baner Pashan Link Road, Pashan- 411021',
      locality: 'Saket',
      parentId: 11720,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'distance',
            fee: 4000,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4000,
        message: '',
        title: 'Delivery Charge',
        amount: '4000',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: 'Closes soon',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '50% OFF',
        subHeader: 'UPTO ₹100',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '350028',
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 5000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '167188',
      name: 'Chinese Karkhana',
      uuid: 'fd521989-d9d9-4b88-8d2f-5b492c98e826',
      city: '6',
      area: 'Baner',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'yvorwgbj7ua6nqfukozi',
      cuisines: ['Chinese', 'Asian', 'Beverages', 'Street Food'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: '19 MINS',
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: 'rice-bowl-factory-pimple-saudagar',
        city: 'pune',
      },
      cityState: '6',
      address:
        'The Chinese Factory  Shop no 4, Kumar Shantiniketan Society, Opp. Amar Serenity, Baner Pashan Link Road, Pashan- 411021',
      locality: 'Pashan Link Road',
      parentId: 61808,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'distance',
            fee: 4000,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4000,
        message: '',
        title: 'Delivery Charge',
        amount: '4000',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: 'Closes soon',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '60% OFF',
        subHeader: 'UPTO ₹100',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '167188',
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.0',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '690657',
      name: 'Effingut Bistro',
      uuid: '1112dee3-098a-48ab-9248-f1d01f7a05bf',
      city: '6',
      area: 'Baner',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: '',
      cuisines: ['Asian', 'Continental'],
      tags: [],
      costForTwo: 80000,
      costForTwoString: '₹800 FOR TWO',
      deliveryTime: 31,
      minDeliveryTime: 31,
      maxDeliveryTime: 31,
      slaString: '31 MINS',
      lastMileTravel: 5,
      slugs: {
        restaurant: 'effingut-bistro-baner-baner',
        city: 'pune',
      },
      cityState: '6',
      address:
        'SHRIKANT SHITOLE CAPITAL BUILDING,SR NO.109/4,GR.FLR+1 FLR +2 FLR,OPP.MY WORLD CUMMINS ROAD,BANER,PUNE ,Aundh,Pune,Maharashtra-411045',
      locality: 'Aundh',
      parentId: 410614,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'distance',
            fee: 6600,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 6600,
        message: '',
        title: 'Delivery Charge',
        amount: '6600',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: 'Closes soon',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=6660397~p=4~eid=00000188-49d9-c9c4-6c5b-c113004a0432',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '60% OFF',
        subHeader: 'UPTO ₹100',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '690657',
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        lastMileTravel: 5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '--',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '359024',
      name: 'Mad over Bowls (MOB)',
      uuid: '7b431b6c-1c34-44d0-bf66-6a1529112fe7',
      city: '6',
      area: 'Aundh',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'fqvwlc842eltfoyy0dxb',
      cuisines: ['Chinese', 'Asian', 'Beverages'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: '19 MINS',
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: 'mad-over-bowls-pimple-saudagar-pimple-saudagar',
        city: 'pune',
      },
      cityState: '6',
      address:
        'The Chinese Factory  Shop no 4, Kumar Shantiniketan Society, Opp. Amar Serenity, Baner Pashan Link Road, Pashan- 411021',
      locality: 'Saket Complex',
      parentId: 21728,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'distance',
            fee: 4000,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4000,
        message: '',
        title: 'Delivery Charge',
        amount: '4000',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: 'Closes soon',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '60% OFF',
        subHeader: 'UPTO ₹100',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '359024',
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.0',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '445211',
      name: 'Chinese By Kilo !',
      uuid: '84e26e81-4714-438a-96db-2ad0fd4c9d57',
      city: '6',
      area: 'Baner',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 't5lmntm3rxtbg0bnjich',
      cuisines: ['Chinese', 'Tibetan', 'Pan-Asian', 'Beverages'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 21,
      minDeliveryTime: 21,
      maxDeliveryTime: 21,
      slaString: '21 MINS',
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: 'the-chinese-monk-baner-baner',
        city: 'pune',
      },
      cityState: '6',
      address:
        'The Chinese Factory  Shop no 4, Kumar Shantiniketan Society, Opp. Amar Serenity, Baner Pashan Link Road, Pashan- 411021',
      locality: 'Pashan Link Road',
      parentId: 235930,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'distance',
            fee: 4000,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4000,
        message: '',
        title: 'Delivery Charge',
        amount: '4000',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: 'Closes soon',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '60% OFF',
        subHeader: 'UPTO ₹100',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '445211',
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
];
